services:
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - "postgres-data:/var/lib/postgresql/data"

volumes:
  postgres-data:
    driver: local
