services:
  redis:
    image: redis
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - "redis-data:/var/lib/redis/data"

volumes:
  redis-data:
    driver: local
