#!/usr/bin/env sh

# @author Isank
# @github https://github.com/isank-a

# Dock
defaults write com.apple.dock tilesize -int 21;
defaults write com.apple.dock largesize -int 63;
killall Dock;

# Keyboard
defaults write -g InitialKeyRepeat -int 15;
defaults write -g KeyRepeat -int 2;

# Screecapture
defaults write com.apple.screencapture type JPG;
