#!/usr/bin/env sh

# @author Isank
# @github https://github.com/isank-a

source ~/.scripts/git-config

configure_git() {

    git config --local user.name "$1"
    git config --local user.email "$2"
}

main() {

    if [ "$1" = "work" ]; then
        configure_git $WORK_USERNAME $WORK_EMAIL
    fi

    if [ "$1" = "personal" ]; then
        configure_git $PERSONAL_USERNAME $PERSONAL_EMAIL
    fi
}

main "$1"
