#!/usr/bin/env sh

# @author Isank
# @github https://github.com/isank-a

/usr/bin/python3 -m pip list --outdated --format=json | jq '.[].name' | xargs -n1 /usr/bin/python3 -m pip install --upgrade;
/usr/bin/python3 -m pip cache purge;

