#!/usr/bin/env sh

# @author Isank
# @github https://github.com/isank-a

if [ $# -eq 1 ]; then
  selected=$1
else
  selected=$(find ~/hacks/** -type d -maxdepth 2 -not \( -path "*.git*" -o -path "*.DS_Store*" -o -path "*.idea*" -o -path "*.gradle*" -o -path "*.mvn*" -o -path "*.github*" \) | fzf)
fi

if [ -z "$selected" ]; then
  exit 0
fi

selected_name=$(basename "$selected" | tr . _)

if [ -z "$TMUX" ]; then
  tmux new -ADs "$selected_name" -c "$selected"
  exit 0
else
  tmux switch-client -t "$selected_name"
  exit 0
fi


