import:
  - ~/.config/alacritty/theme.yaml
window:
  opacity: 1.0
  startup_mode: Windowed
  decorations: Full
  dynamic_padding: true
cursor:
  style:
    shape: Underline 
    blinking: On 
font:
  normal:
    family: Fira Cousine
    style: Regular
  size: 14
  offset:
    x: 0
    y: 9
live_config_reload: true
