live_config_reload = true

[cursor]
unfocused_hollow = false

[cursor.style]
blinking = "On"
shape = "Underline"

[font]
size = 15

[font.normal]
family = "Fira Cousine"
style = "Regular"

[font.offset]
x = 0
y = 6

[font.glyph_offset]
x = 0
y = 3

[window]
decorations = "Full"
dynamic_padding = true
opacity = 1.0
startup_mode = "Windowed"

[window.padding]
x = 0
y = 0
