import:
  - ~/.config/alacritty/theme.yaml
window:
  opacity: 1.0
  startup_mode: Windowed
  decorations: Full
  dynamic_padding: true
  padding:
    x: 3
    y: 3
cursor:
  style:
    shape: Underline 
    blinking: On
  unfocused_hollow: false
font:
  normal:
    family: Fira Cousine
    style: Regular
  size: 14
  offset:
    x: 1
    y: 9
live_config_reload: true