import:
  - ~/.config/alacritty/theme.yaml
window:
  opacity: 1.0
  startup_mode: Windowed
  decorations: none
  dynamic_padding: true
cursor:
  style:
    shape: Underline 
    blinking: On 
font:
  normal:
    family: Cousine Nerd Font Mono
    style: Regular
  size: 13
live_config_reload: true
