import:
  - ~/.config/alacritty/theme.yaml
window:
  opacity: 1.0
  startup_mode: Windowed
  decorations: none
  dynamic_padding: true
  padding:
    x: 5
    y: 5
cursor:
  style:
    shape: Block 
    blinking: On 
font:
  normal:
    family: Monaco 
  size: 12
live_config_reload: true
