[colors.bright]
black = "#6E7681"
blue = "#91CBFF"
cyan = "#39C5CF"
green = "#4AE168"
magenta = "#CB9EFF"
red = "#FFB1AF"
white = "#D9DEE3"
yellow = "#F7C843"

[colors.cursor]
cursor = "#F0F8FF"
text = "#0A0C10"

[colors.normal]
black = "#3B3C36"
blue = "#71B7FF"
cyan = "#39C5CF"
green = "#26CD4D"
magenta = "#CB9EFF"
red = "#FF9492"
white = "#D9DEE3"
yellow = "#F0B72F"

[colors.primary]
background = "#0A0C10"
foreground = "#F0F8FF"
