colors:
  # Default colors
  primary:
    background: '#0A0C10'
    foreground: '#E6DBAC'

  # Cursor colors
  #
  # These will only be used when the `custom_cursor_colors` field is set to `true`.
  cursor:
    text: '#0A0C10'
    cursor: '#E6DBAC'

  # Normal colors
  normal:
    black: '#3B3C36'
    red: '#FF9492'
    green: '#26CD4D'
    yellow: '#F0B72F'
    blue: '#71B7FF'
    magenta: '#CB9EFF'
    cyan: '#39C5CF'
    white: '#D9DEE3'

  # Bright colors
  bright:
    black: '#6E7681'
    red: '#FFB1AF'
    green: '#4AE168'
    yellow: '#F7C843'
    blue: '#91CBFF'
    magenta: '#CB9EFF'
    cyan: '#39C5CF'
    white: '#D9DEE3'