services:
  elasticsearch:
    image: elasticsearch:7.13.3
    container_name: elasticsearch
    ports:
      - "9200:9200"
    environment:
      - "discovery.type=single-node"

  kibana:
    image: kibana:7.13.3
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      - "ELASTICSEARCH_HOSTS=http://localhost:9200"
    depends_on:
      - "elasticsearch"
