format = """
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status
$character"""

[character]
success_symbol = "[❯](red)[❯](yellow)[❯](green)"
error_symbol = "[❯](red)[❯](red)[❯](red)"

